#!/bin/sh

if [ -f $1.lpz ]; then
    if [ ! $2 ] && [ $1.lpz -ot ./ctmp/$1.prog ]; then  
		./ctmp/$1.prog
 	else
        if [ ! -d ctmp ]; then
            mkdir ctmp
            cat > ./ctmp/lang.h <<CODE
                                                                                                #include <stdio.h>            
/**----------      lapooza!  english computer language!                      **/         
/**                                                                          **/            #define                    to_equal                             =
/**     want the speed of C, but the ease of use and keywords of basic?      **/            #define                       is_equal                        ==
/**        Term definition:                                                  **/            #define                   not_equal                         !=
/**            Run a program... type: lapozza program.lpz                    **/            #define            are_equal
/**            Begin a .lpz program with "Welcome"                           **/            #define what 
/**            End it with Thanks                                            **/            #define works )==0){
/**            Inbetween:                                                    **/            #define comparing strcmp(
/**               Print to screen type - write "my message" please           **/            #define is );
/**               To setup a variable: gimme my_var swell                    **/            #define if if(
/**         More information in the demo file for now.                       **/                                                                                            #define otherwise } else {
/**                                                                          **/                                                                                            #define ok }
/**                                                                          **/                                                                                            #define then ){
/**                                                                          **/                                                                                            #define Calculate printf("Calculated:\n%d\n", 
/**                                                                          **/                                                                                            #define and +
/**                                                                          **/                                                                                            #define Thanks  lexit: enter return(0); }
/**                                                                          **/                                                                                            #define Welcome  int main(void){
                                                                                            #define true 1
                                                                                            #define you  true
                                                                                            #define rock true
                                                                                            #define minus -
                                                                                            #define add +
                                                                                            #define divided /
                                                                                            #define by
                                                                                            #define to 
                                                                                            #define gimme char 
                                                                                            #define swell [200];
                                                                                            #define something (
                                                                                            #define yeah );
                                                                                            #define poot printf("\nplrrb\n");
                                                                                            #define grab scanf("%s", 
                                                                                            #define ask_for grab 
                                                                                            #define write printf("%s\n", 
                                                                                            #define with ,
                                                                                            #define clear enter
                                                                                            #define enter printf("\n");
                                                                                            #define tis_all }
                                                                                            #define please );
                                                                                            #define thanks ;
                                                                                            #define exit goto lexit;
                                                                                            #define section
                                                                                            #define end }
                                                                                            #define also } else if                                                                                        
                                                                                            #define something (  
                                                                                            #define yeah ); 
                                                                                            #define poot printf("\nplrrb\n"); 
                                                                                            #define grab scanf("%s",  
CODE
    fi
        cd ./ctmp
        echo '#include "lang.h"' > $1.src.c
        echo '#include <stdio.h>' >> $1.src.c
        cat ../$1.lpz >> $1.src.c
        echo '' > $1.prog
        gcc $1.src.c -o $1.prog
        chmod u+x $1.prog
        ./$1.prog
	fi
else
    echo 'USAGE: .lpz file not found as first argument to run.'
fi

